include: package:lint/analysis_options.yaml

analyzer:
   plugins:
     - dart_code_metrics
     
linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: true

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maintainability-index: 50
    maximum-nesting: 5
    number-of-parameters: 5
    source-lines-of-code: 50
  metrics-exclude:
    - test/analyzer_plugin/**
    - test/analyzers/**
    - test/cli/**
    - test/config_builder/**
    - test/helpers/**
    - test/reporters/**
    - test/utils/**
    - test/resources/*
    - test/*
  rules:
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - no-object-declaration
    - prefer-conditional-expressions
    - prefer-trailing-comma