name: characters_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.2
  flutter_modular: ^4.1.0
  mobx: ^2.0.4

dev_dependencies:
  build_runner: ^2.1.4
  dart_code_metrics: ^4.2.0-dev.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.3
  mocktail: ^0.1.4

flutter:
  uses-material-design: true
